# --------------------------------------------------------------------
#  ePaper Display – PowerOcean Dashboard
#  Version: 1.7
#  Änderungen:
#    - Warmwasser wieder eingeblendet (Label "Warmwasser", Einheit °C)
#    - Drei-Spalten-Verbrauchsblock erweitert um Warmwasser
#    - Vollständige Zentrierungs- und Aufrücklogik übernommen
#    - Rest: identisch zu v1.6
# --------------------------------------------------------------------

esphome:
  name: epaper
  friendly_name: ePaper

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "JpvERJsHgGmgv6zi3tPtTDR7cXTkMIcoAQmbiOCEFxw="

ota:
  - platform: esphome
    password: "7c8ebe25a7a6df2e6666c3819e572e2b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Epaper Fallback Hotspot"
    password: "hCW8fSx9zqiz"

captive_portal:

font:
  - file: "gfonts://Inter@600"
    id: myFont
    size: 40

  - file: "gfonts://Inter@700"
    id: smallFont
    size: 30

  - file: "gfonts://Inter@600"
    id: tinyFont
    size: 28

text_sensor:
  - platform: homeassistant
    entity_id: sensor.powerocean_sysloadpwr
    id: SysLoadPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_sysgridpwr
    id: SysGridPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bppwr
    id: BatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_mpptpwr
    id: PVPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bpsoc
    id: BatSOC
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_heizstab_power
    id: HeatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.shelly_plug_mercedes_eqa_250_power
    id: EQAPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.pufferspeicher_oben
    id: WarmWasser
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_zeit_bis_batterie_voll
    id: ZeitBisVoll
    internal: true

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: 30s
    lambda: |-
      // ---- Helpers ----
      auto as_int = [](const std::string &s) -> int {
        if (s.empty() || s == "unavailable" || s == "unknown" ||
            s == "None" || s == "none" || s == "nan" || s == "NaN")
          return 0;
        return (int) lroundf(strtof(s.c_str(), nullptr));
      };

      auto fmt_power = [](char *buf, int value) {
        if (abs(value) >= 1000)
          sprintf(buf, "%.2f kW", value / 1000.0f);
        else
          sprintf(buf, "%d W", value);
      };

      auto clamp = [](int v){ return std::min(100, std::max(0, v)); };

      // ---- Werte laden ----
      int vHaus = as_int(id(SysLoadPwr).state);
      int vPV   = as_int(id(PVPwr).state);
      int vGrid = as_int(id(SysGridPwr).state);
      int vHeat = as_int(id(HeatPwr).state);
      int vBat  = as_int(id(BatPwr).state);
      int vSOC  = as_int(id(BatSOC).state);
      int vEQA  = as_int(id(EQAPwr).state);
      int vWW   = as_int(id(WarmWasser).state);
      std::string sZeit = id(ZeitBisVoll).state;

      int vBatMinus = (vBat < 0) ? -vBat : 0;
      int vBatPlus  = (vBat > 0) ?  vBat : 0;

      vHaus = vHaus - vHeat;

      int vBezug       = (vGrid > 0) ? vGrid : 0;
      int vEinspeisung = (vGrid < 0) ? abs(vGrid) : 0;

      int pv_pct   = clamp((int) lroundf((vPV   / 12600.0f) * 100.0f));
      int heat_pct = clamp((int) lroundf((vHeat /  9000.0f) * 100.0f));
      int grid_pct = (vGrid < 0) ? clamp((int) lroundf((abs(vGrid) / 7560.0f) * 100.0f)) : 0;

      // ---- Formatstrings ----
      char sHaus[20], sPV[20], sHeat[20], sEQA[20],
           sBezug[20], sEins[20], sBatMinusStr[20], sBatPlusStr[20];

      fmt_power(sHaus, vHaus);
      fmt_power(sPV,   vPV);
      fmt_power(sHeat, vHeat);
      fmt_power(sEQA,  vEQA);
      fmt_power(sBezug, vBezug);
      fmt_power(sEins,  vEinspeisung);
      fmt_power(sBatMinusStr, vBatMinus);
      fmt_power(sBatPlusStr,  vBatPlus);

      const int screen_w = 800;
      const int cw       = 18;

      // ---- Zentrierte Blockfunktionen ----
      auto draw_block3 = [&](int yLabel, int yValue,
                             const char *label1, const char *value1, bool show1,
                             const char *label2, const char *value2, bool show2,
                             const char *label3, const char *value3, bool show3) {
        int count = (show1?1:0) + (show2?1:0) + (show3?1:0);
        if (count == 0) return;
        int seg_w = screen_w / count;
        int idx = 0;

        auto draw_one = [&](const char *lbl, const char *val){
          int sx = idx * seg_w + seg_w/2;
          it.printf(sx - strlen(lbl)*cw/2, yLabel, id(myFont), "%s", lbl);
          it.printf(sx - strlen(val)*cw/2, yValue, id(myFont), "%s", val);
          idx++;
        };
        if (show1) draw_one(label1, value1);
        if (show2) draw_one(label2, value2);
        if (show3) draw_one(label3, value3);
      };

      // ---- Zufluss (oben) ----
      char pv_full[32], bez_full[32], bat_full[32];
      sprintf(pv_full,  "%s (%d%%)", sPV, pv_pct);
      sprintf(bez_full, "%s",        sBezug);
      sprintf(bat_full, "%s",        sBatMinusStr);

      draw_block3(
        20, 60,
        "Solar",     pv_full,  (vPV       != 0),
        "Netzbezug", bez_full, (vBezug    != 0),
        "Batterie",  bat_full, (vBatMinus != 0)
      );

      // Trenner
      it.filled_rectangle(10, 130, 780, 5);

      // ---- Verbraucherblock 1 ----
      char h_full[32], heat_full[32], eqa_full[32];
      sprintf(h_full, "%s", sHaus);
      sprintf(heat_full, "%s (%d%%)", sHeat, heat_pct);
      sprintf(eqa_full, "%s", sEQA);

      draw_block3(
        160, 200,
        "Haus",     h_full,    (vHaus != 0),
        "Heizstab", heat_full, (vHeat != 0),
        "EQA",      eqa_full,  (vEQA  != 0)
      );

      // ---- Verbraucherblock 2: jetzt mit Warmwasser ----
      char batp_full[32], eins_full[32], ww_full[32];
      sprintf(batp_full, "%s", sBatPlusStr);
      sprintf(ww_full, "%d °C", vWW);

      if (vEinspeisung > 0)
        sprintf(eins_full, "%s (%d%%)", sEins, grid_pct);
      else
        sprintf(eins_full, "%s", sEins);

      draw_block3(
        250, 290,
        "Batterie (laden)", batp_full, (vBatPlus     != 0),
        "Einspeisung",      eins_full, (vEinspeisung > 0),
        "Warmwasser",       ww_full,   true
      );

      // ---- SOC-Bereich ----
      const int bx = 50;
      const int by = 440;
      const int bw = 700;
      const int bh = 20;

      char sSoc[64];

      if (!sZeit.empty() && sZeit != "unknown" && sZeit != "unavailable") {
        float h = strtof(sZeit.c_str(), nullptr);
        if (h > 0 && h < 999) {
          int hh = floor(h);
          int mm = lround((h - hh)*60.0f);
          if (mm >= 60) { mm -= 60; hh++; }
          sprintf(sSoc, "Batterie: %d%% | %dh %02dmin bis voll", vSOC, hh, mm);
        } else {
          sprintf(sSoc, "Batterie: %d%%", vSOC);
        }
      } else {
        sprintf(sSoc, "Batterie: %d%%", vSOC);
      }

      int soc_x = bx + bw/2 - strlen(sSoc) * cw / 2;
      it.printf(soc_x, by - 40, id(tinyFont), "%s", sSoc);

      it.rectangle(bx, by, bw, bh);

      int fw = bw * clamp(vSOC) / 100;
      if (fw > 0) it.filled_rectangle(bx, by, fw, bh);

      for (int i = 0; i <= 10; i++) {
        int tx = bx + (bw*i)/10;
        it.line(tx, by + bh + 2, tx, by + bh + 8);
      }

      int marks[5] = {0,25,50,75,100};
      for (int i = 0; i < 5; i++) {
        int tx = bx + (bw * marks[i]) / 100;
        it.line(tx,     by + bh - 2, tx,     by + bh + 10);
        it.line(tx + 1, by + bh - 2, tx + 1, by + bh + 10);
      }
