# --------------------------------------------------------------------
#  ePaper Display – PowerOcean Dashboard
#  Version: 1.30
#  Änderungen:
#    - Zufluss: Energie und Euro-Wert getrennt in 3. und 4. Zeile
#    - Euro-Wert ohne Klammern (z.B. "1.67 €")
#    - Trennerlinie auf y=140 verschoben, damit genug Platz ist
# --------------------------------------------------------------------

esphome:
  name: epaper
  friendly_name: ePaper

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "JpvERJsHgGmgv6zi3tPtTDR7cXTkMIcoAQmbiOCEFxw="

ota:
  - platform: esphome
    password: "7c8ebe25a7a6df2e6666c3819e572e2b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Epaper Fallback Hotspot"
    password: "hCW8fSx9zqiz"

captive_portal:

font:
  - file: "gfonts://Inter@600"
    id: myFont
    size: 40

  - file: "gfonts://Inter@700"
    id: smallFont
    size: 30

  - file: "gfonts://Inter@600"
    id: tinyFont
    size: 28

text_sensor:
  - platform: homeassistant
    entity_id: sensor.powerocean_sysloadpwr
    id: SysLoadPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_sysgridpwr
    id: SysGridPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bppwr
    id: BatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_mpptpwr
    id: PVPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bpsoc
    id: BatSOC
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_heizstab_power
    id: HeatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.shelly_plug_mercedes_eqa_250_power
    id: EQAPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.pufferspeicher_oben
    id: WarmWasser
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_zeit_bis_batterie_voll
    id: ZeitBisVoll
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_pv1_energy_today
    id: PV1EnergyToday
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_pv2_energy_today
    id: PV2EnergyToday
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_battery_discharge_today
    id: BatDischargeToday
    internal: true
  - platform: homeassistant
    entity_id: sensor.iometer_gesamtbezug_today
    id: GridEnergyToday
    internal: true
  - platform: homeassistant
    entity_id: input_number.strompreis
    id: Strompreis
    internal: true

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: 30s
    lambda: |-
      // ---- Helpers ----
      auto as_int = [](const std::string &s) -> int {
        if (s.empty() || s == "unavailable" || s == "unknown" ||
            s == "None" || s == "none" || s == "nan" || s == "NaN")
          return 0;
        return (int) lroundf(strtof(s.c_str(), nullptr));
      };

      auto as_float = [](const std::string &s) -> float {
        if (s.empty() || s == "unavailable" || s == "unknown" ||
            s == "None" || s == "none" || s == "nan" || s == "NaN")
          return 0.0f;
        return strtof(s.c_str(), nullptr);
      };

      auto fmt_power = [](char *buf, int value) {
        if (abs(value) >= 1000)
          sprintf(buf, "%.2f kW", value / 1000.0f);
        else
          sprintf(buf, "%d W", value);
      };

      auto clamp = [](int v){ return std::min(100, std::max(0, v)); };

      // --- Zeichenbreiten-LUT für tinyFont (Inter @ 28) ---
      auto tiny_char_width = [](char c) -> int {
        switch (c) {
          // Ziffern
          case '0': case '8': case '9': return 15;
          case '1':                     return 11;
          case '2': case '3': case '4':
          case '5': case '6': case '7': return 14;

          // Großbuchstaben
          case 'A': case 'B': case 'D': case 'E':
          case 'H': case 'K': case 'N': case 'R':
          case 'U': case 'V': case 'X': case 'Y': case 'Z':
            return 16;
          case 'C': case 'G': case 'O': case 'Q':
            return 17;
          case 'F': case 'L': case 'P': case 'S': case 'T':
            return 15;
          case 'I': case 'J':
            return 11;
          case 'M': case 'W':
            return 19;

          // Kleinbuchstaben
          case 'a': case 'c': case 'e': case 'o':
            return 13;
          case 'b': case 'd': case 'g': case 'h':
          case 'n': case 'p': case 'q': case 'u':
            return 14;
          case 'i': case 'j':
            return 8;
          case 'k': case 'r': case 's': case 't':
            return 12;
          case 'l':
            return 7;
          case 'm':
            return 18;
          case 'v': case 'x':
            return 13;
          case 'w':
            return 17;
          case 'y': case 'z':
            return 12;

          // Satzzeichen / Einheiten
          case '(': case ')': return 10;
          case '.': case ',': return 7;
          case ':':           return 7;
          case ' ':           return 8;
          case '€':           return 14;

          default: return 14; // Fallback
        }
      };

      auto tiny_text_width = [&](const std::string &s) -> int {
        int sum = 0;
        for (size_t i = 0; i < s.size(); i++) {
          sum += tiny_char_width(s[i]);
        }
        return sum;
      };

      // ---- Werte laden ----
      int   vHaus = as_int(id(SysLoadPwr).state);
      int   vPV   = as_int(id(PVPwr).state);
      int   vGrid = as_int(id(SysGridPwr).state);
      int   vHeat = as_int(id(HeatPwr).state);
      int   vBat  = as_int(id(BatPwr).state);
      int   vSOC  = as_int(id(BatSOC).state);
      int   vEQA  = as_int(id(EQAPwr).state);
      int   vWW   = as_int(id(WarmWasser).state);

      float vPV1Today    = as_float(id(PV1EnergyToday).state);
      float vPV2Today    = as_float(id(PV2EnergyToday).state);
      float vBatDisToday = as_float(id(BatDischargeToday).state);
      float vGridToday   = as_float(id(GridEnergyToday).state);
      float vPrice       = as_float(id(Strompreis).state);

      std::string sZeit = id(ZeitBisVoll).state;

      int vBatMinus = (vBat < 0) ? -vBat : 0;
      int vBatPlus  = (vBat > 0) ?  vBat : 0;

      // ---- Hausverbrauch berechnen ----
      vHaus = vHaus - vHeat - vEQA;

      // Netzwerte
      int vBezug       = (vGrid > 0) ? vGrid : 0;
      int vEinspeisung = (vGrid < 0) ? abs(vGrid) : 0;

      // Prozentwerte
      int pv_pct   = clamp((int) lroundf((vPV   / 12600.0f) * 100.0f));
      int heat_pct = clamp((int) lroundf((vHeat /  9000.0f) * 100.0f));
      int grid_pct = (vGrid < 0)
                     ? clamp((int) lroundf((abs(vGrid) / 7560.0f) * 100.0f))
                     : 0;

      // Batterie-Lade-Prozent (100 % = 5090 W)
      int batplus_pct = (vBatPlus > 0)
                        ? clamp((int) lroundf((vBatPlus / 5090.0f) * 100.0f))
                        : 0;

      // Tageserträge + Werte
      float pv_today   = vPV1Today + vPV2Today;
      float pv_value   = pv_today   * vPrice;

      float bat_today  = vBatDisToday;
      float bat_value  = bat_today  * vPrice;

      float grid_today = vGridToday;
      float grid_value = grid_today * vPrice;

      // ---- Formatstrings für Leistungen ----
      char sHaus[20], sPV[20], sHeat[20], sEQA[20],
           sBezug[20], sEins[20], sBatMinusStr[20], sBatPlusStr[20];

      fmt_power(sHaus, vHaus);
      fmt_power(sPV,   vPV);
      fmt_power(sHeat, vHeat);
      fmt_power(sEQA,  vEQA);
      fmt_power(sBezug, vBezug);
      fmt_power(sEins,  vEinspeisung);
      fmt_power(sBatMinusStr, vBatMinus);
      fmt_power(sBatPlusStr,  vBatPlus);

      const int screen_w = 800;
      const int cw_big   = 18;  // myFont (für Labels/Werte im Verbrauchsteil)

      // ----------------------------------------------------
      // ZUFLUSS-BEREICH (Solar / Netz / Batterie) – immer sichtbar
      // ----------------------------------------------------
      int pSolar = (vPV       > 0) ? vPV       : 0;
      int pBezug = (vBezug    > 0) ? vBezug    : 0;
      int pBatIn = (vBatMinus > 0) ? vBatMinus : 0;

      int totalIn = pSolar + pBezug + pBatIn;

      int shareSolar = 0, shareBezug = 0, shareBatIn = 0;
      if (totalIn > 0) {
        shareSolar = (int) lroundf(pSolar * 100.0f / totalIn);
        shareBezug = (int) lroundf(pBezug * 100.0f / totalIn);
        shareBatIn = (int) lroundf(pBatIn * 100.0f / totalIn);
      }

      int active_inflow_count =
          (pSolar > 0 ? 1 : 0) +
          (pBezug > 0 ? 1 : 0) +
          (pBatIn > 0 ? 1 : 0);

      if (true) {
        int inflow_count = 3;
        int seg_w = screen_w / inflow_count;
        int idx   = 0;

        const int yLabel  = 10;
        const int yPower  = 40;
        const int yEnergy = 80;
        const int yEuro   = 110;

        auto draw_inflow = [&](const char* label,
                               const char* value,
                               const std::string &energy_text,
                               const std::string &value_text) {
          int cx = idx * seg_w + seg_w / 2;

          std::string lbl_str(label);
          int lbl_px = tiny_text_width(lbl_str);
          int val_px = strlen(value) * cw_big;

          it.printf(cx - lbl_px/2, yLabel,  id(tinyFont), "%s", label);
          it.printf(cx - val_px/2, yPower,  id(myFont),   "%s", value);

          if (!energy_text.empty()) {
            int e_px = tiny_text_width(energy_text);
            it.printf(cx - e_px/2, yEnergy, id(tinyFont), "%s", energy_text.c_str());
          }

          if (!value_text.empty()) {
            int v_px = tiny_text_width(value_text);
            it.printf(cx - v_px/2, yEuro,   id(tinyFont), "%s", value_text.c_str());
          }

          idx++;
        };

        // Power-Strings
        char pv_full[32], bez_full[32], bat_full[32];
        if (vPV > 0)
          sprintf(pv_full, "%s (%d%%)", sPV, pv_pct);
        else
          sprintf(pv_full, "%s", sPV);
        sprintf(bez_full, "%s", sBezug);
        sprintf(bat_full, "%s", sBatMinusStr);

        // Energie- und Euro-Strings
        char buf[32];
        std::string pv_energy_str, pv_value_str;
        std::string bez_energy_str, bez_value_str;
        std::string bat_energy_str, bat_value_str;

        sprintf(buf, "%.2f kWh", pv_today);
        pv_energy_str = buf;
        sprintf(buf, "%.2f €", pv_value);
        pv_value_str = buf;

        sprintf(buf, "%.2f kWh", grid_today);
        bez_energy_str = buf;
        sprintf(buf, "%.2f €", grid_value);
        bez_value_str = buf;

        sprintf(buf, "%.2f kWh", bat_today);
        bat_energy_str = buf;
        sprintf(buf, "%.2f €", bat_value);
        bat_value_str = buf;

        // Labels (mit Prozent nur bei >1 aktivem Zufluss)
        char lblSolar[32]      = "Solar";
        char lblBezug[32]      = "Netz";
        char lblBatterieIn[32] = "Batterie";

        if (totalIn > 0 && active_inflow_count > 1) {
          if (shareSolar > 0)
            sprintf(lblSolar, "Solar %d%%", shareSolar);
          if (shareBezug > 0)
            sprintf(lblBezug, "Netz %d%%", shareBezug);
          if (shareBatIn > 0)
            sprintf(lblBatterieIn, "Batterie %d%%", shareBatIn);
        }

        // Reihenfolge: Solar – Netz – Batterie
        idx = 0;
        draw_inflow(lblSolar,      pv_full,  pv_energy_str,  pv_value_str);
        draw_inflow(lblBezug,      bez_full, bez_energy_str, bez_value_str);
        draw_inflow(lblBatterieIn, bat_full, bat_energy_str, bat_value_str);
      }

      // Trenner etwas nach unten verschoben
      it.filled_rectangle(10, 140, 780, 5);

      // ----------------------------------------------------
      // VERBRAUCHER – dynamische 2-Zeilen-Verteilung
      // ----------------------------------------------------
      char h_full[32], heat_full[32], eqa_full[32], ww_full[32];
      sprintf(h_full,    "%s", sHaus);
      sprintf(heat_full, "%s (%d%%)", sHeat, heat_pct);
      sprintf(eqa_full,  "%s", sEQA);
      sprintf(ww_full,   "%d °C", vWW);

      char batp_full[32], eins_full[32];

      if (vBatPlus > 0)
        sprintf(batp_full, "%s (%d%%)", sBatPlusStr, batplus_pct);
      else
        sprintf(batp_full, "%s", sBatPlusStr);

      if (vEinspeisung > 0)
        sprintf(eins_full, "%s (%d%%)", sEins, grid_pct);
      else
        sprintf(eins_full, "%s", sEins);

      // Verbraucher-Anteile (ohne Warmwasser)
      int pHausC = (vHaus      > 0) ? vHaus      : 0;
      int pHeatC = (vHeat      > 0) ? vHeat      : 0;
      int pEQAC  = (vEQA       > 0) ? vEQA       : 0;
      int pBatC  = (vBatPlus   > 0) ? vBatPlus   : 0;
      int pEinsC = (vEinspeisung > 0) ? vEinspeisung : 0;

      int totalCons = pHausC + pHeatC + pEQAC + pBatC + pEinsC;

      int shareHaus = 0, shareHeat = 0, shareEQA = 0, shareBatC = 0, shareEins = 0;
      if (totalCons > 0) {
        shareHaus = (int) lroundf(pHausC * 100.0f / totalCons);
        shareHeat = (int) lroundf(pHeatC * 100.0f / totalCons);
        shareEQA  = (int) lroundf(pEQAC  * 100.0f / totalCons);
        shareBatC = (int) lroundf(pBatC  * 100.0f / totalCons);
        shareEins = (int) lroundf(pEinsC * 100.0f / totalCons);
      }

      int consumer_count =
          (pHausC  > 0 ? 1 : 0) +
          (pHeatC  > 0 ? 1 : 0) +
          (pEQAC   > 0 ? 1 : 0) +
          (pBatC   > 0 ? 1 : 0) +
          (pEinsC  > 0 ? 1 : 0);

      // Labels für Verbraucher
      char lblHaus[32]       = "Haus";
      char lblHeiz[32]       = "Heizstab";
      char lblEQA[32]        = "EQA";
      char lblWW[32]         = "Warmwasser";
      char lblBatVerbr[32]   = "Batterie";
      char lblEinspeisung[32]= "Einspeisung";

      if (totalCons > 0 && consumer_count > 1) {
        if (shareHaus > 0)
          sprintf(lblHaus, "Haus %d%%", shareHaus);
        if (shareHeat > 0)
          sprintf(lblHeiz, "Heizstab %d%%", shareHeat);
        if (shareEQA > 0)
          sprintf(lblEQA, "EQA %d%%", shareEQA);
        if (shareBatC > 0)
          sprintf(lblBatVerbr, "Batterie %d%%", shareBatC);
        if (shareEins > 0)
          sprintf(lblEinspeisung, "Einspeisung %d%%", shareEins);
      }

      struct Item {
        const char* label;
        const char* value;
        bool show;
      };

      Item items[6] = {
        { lblHaus,        h_full,    (vHaus != 0) },
        { lblHeiz,        heat_full, (vHeat != 0) },
        { lblEQA,         eqa_full,  (vEQA  != 0) },
        { lblWW,          ww_full,   true        },
        { lblBatVerbr,    batp_full, (vBatPlus     != 0) },
        { lblEinspeisung, eins_full, (vEinspeisung > 0) }
      };

      int vis_idx[6];
      int n_vis = 0;
      for (int i = 0; i < 6; i++) {
        if (items[i].show) vis_idx[n_vis++] = i;
      }

      if (n_vis > 0) {
        int row1=0, row2=0;
        switch(n_vis){
          case 1: row1=1; row2=0; break;
          case 2: row1=2; row2=0; break;
          case 3: row1=2; row2=1; break;
          case 4: row1=2; row2=2; break;
          case 5: row1=3; row2=2; break;
          default: row1=3; row2=n_vis-3; break;
        }

        auto draw_row = [&](int start, int count, int yL, int yV){
          if (count<=0) return;
          int seg_w = screen_w / count;
          for (int k=0;k<count;k++){
            Item &it_item = items[vis_idx[start+k]];
            int cx = k*seg_w + seg_w/2;
            int lbl_px = strlen(it_item.label)*cw_big;
            int val_px = strlen(it_item.value)*cw_big;
            it.printf(cx - lbl_px/2, yL, id(myFont), "%s", it_item.label);
            it.printf(cx - val_px/2, yV, id(myFont), "%s", it_item.value);
          }
        };

        draw_row(0, row1, 160, 200);
        draw_row(row1, row2, 250, 290);
      }

      // ----------------------------------------------------
      // SOC-BALKEN
      // ----------------------------------------------------
      const int bx=50, by=440, bw=700, bh=20;

      char sSoc[64];
      if (!sZeit.empty() && sZeit!="unknown" && sZeit!="unavailable"){
        float h = strtof(sZeit.c_str(), nullptr);
        if (h>0 && h<999){
          int hh = (int)floor(h);
          int mm = (int)lround((h-hh)*60.0f);
          if (mm>=60){ mm-=60; hh++; }
          sprintf(sSoc,"Batterie: %d%% | %dh %02dmin bis voll", vSOC, hh, mm);
        } else {
          sprintf(sSoc,"Batterie: %d%%", vSOC);
        }
      } else {
        sprintf(sSoc,"Batterie: %d%%", vSOC);
      }

      std::string soc_str = sSoc;
      int soc_px = tiny_text_width(soc_str);
      int soc_x  = bx + bw/2 - soc_px/2;
      it.printf(soc_x, by-40, id(tinyFont), "%s", sSoc);

      it.rectangle(bx,by,bw,bh);

      int fw = bw * clamp(vSOC)/100;
      if (fw>0) it.filled_rectangle(bx,by,fw,bh);

      // Kleine Ticks 0–90 %
      for (int i=0;i<=9;i++){
        int tx = bx + (bw*i)/10;
        it.line(tx, by+bh+2, tx, by+bh+8);
      }

      // Dicke Ticks bei 0/25/50/75/100 (100% -2 px)
      int marks[5]={0,25,50,75,100};
      for (int i=0;i<5;i++){
        int p = marks[i];
        int tx = bx + (bw*p)/100;
        if (p==100) tx -= 2;
        it.line(tx,     by+bh-2, tx,     by+bh+10);
        it.line(tx + 1, by+bh-2, tx + 1, by+bh+10);
      }
