esphome:
  name: epaper
  friendly_name: ePaper

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "JpvERJsHgGmgv6zi3tPtTDR7cXTkMIcoAQmbiOCEFxw="

ota:
  - platform: esphome
    password: "7c8ebe25a7a6df2e6666c3819e572e2b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Epaper Fallback Hotspot"
    password: "hCW8fSx9zqiz"

captive_portal:

font:
  - file: "gfonts://Inter@600"
    id: myFont
    size: 40
  - file: "gfonts://Inter@700"
    id: smallFont
    size: 30
  - file: "gfonts://Inter@500"
    id: tinyFont
    size: 24

text_sensor:
  - platform: homeassistant
    entity_id: sensor.powerocean_sysloadpwr
    id: SysLoadPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_sysgridpwr
    id: SysGridPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bppwr
    id: BatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_mpptpwr
    id: PVPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_bpsoc
    id: BatSOC
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_heizstab_power
    id: HeatPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.shelly_plug_mercedes_eqa_250_power
    id: EQAPwr
    internal: true
  - platform: homeassistant
    entity_id: sensor.pufferspeicher_oben
    id: WarmWasser
    internal: true
  - platform: homeassistant
    entity_id: sensor.powerocean_zeit_bis_batterie_voll
    id: ZeitBisVoll
    internal: true

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: 30s
    lambda: |-
      // ---- Helpers ----
      auto as_int = [](const std::string &s) -> int {
        if (s.empty() || s == "unavailable" || s == "unknown" || s == "None" ||
            s == "none" || s == "nan" || s == "NaN") {
          return 0;
        }
        return (int) lroundf(strtof(s.c_str(), nullptr));
      };

      auto fmt_power = [](char *buf, int value) {
        if (abs(value) >= 1000) {
          sprintf(buf, "%.2f kW", value / 1000.0f);
        } else {
          sprintf(buf, "%d W", value);
        }
      };

      auto clamp = [](int v){ return std::min(100, std::max(0, v)); };

      // ---- Werte holen ----
      int vHaus = as_int(id(SysLoadPwr).state);
      int vPV   = as_int(id(PVPwr).state);
      int vGrid = as_int(id(SysGridPwr).state);
      int vHeat = as_int(id(HeatPwr).state);
      int vBat  = as_int(id(BatPwr).state);
      int vSOC  = as_int(id(BatSOC).state);
      int vEQA  = as_int(id(EQAPwr).state);
      int vWW   = as_int(id(WarmWasser).state);
      std::string sZeit = id(ZeitBisVoll).state;

      // Haus ohne Heizstab anzeigen
      vHaus = vHaus - vHeat;

      // Bezug/Einspeisung aufspalten
      int vBezug       = (vGrid > 0) ? vGrid : 0;
      int vEinspeisung = (vGrid < 0) ? abs(vGrid) : 0;

      // Prozentwerte
      int pv_pct   = clamp((int) lroundf((vPV   / 12600.0f) * 100.0f));
      int heat_pct = clamp((int) lroundf((vHeat /  9000.0f) * 100.0f));
      int grid_pct = (vGrid < 0) ? clamp((int) lroundf((abs(vGrid) / 7560.0f) * 100.0f)) : 0;

      // Formatpuffer
      char sHaus[20], sPV[20], sHeat[20], sGrid[20], sBat[20], sEQA[20], sBezug[20], sEins[20];

      fmt_power(sHaus, vHaus);
      fmt_power(sPV,   vPV);
      fmt_power(sHeat, vHeat);
      fmt_power(sGrid, vGrid);
      fmt_power(sBat,  vBat);
      fmt_power(sEQA,  vEQA);
      fmt_power(sBezug, vBezug);
      fmt_power(sEins,  vEinspeisung);

      // ---- Anzeige ----
      // Formatierungstexte für die Boxen vorbereiten
      char sPvExtra[40];
      snprintf(sPvExtra, sizeof(sPvExtra), "Auslastung: %d%%", pv_pct);

      char sHausExtra[64];
      snprintf(sHausExtra, sizeof(sHausExtra), "zzgl. Heizstab: %s", sHeat);

      char sHeatExtra[32];
      snprintf(sHeatExtra, sizeof(sHeatExtra), "Last: %d%%", heat_pct);

      char sGridStatus[40];
      if (vGrid < 0)
        snprintf(sGridStatus, sizeof(sGridStatus), "Export: %d%%", grid_pct);
      else if (vGrid > 0)
        snprintf(sGridStatus, sizeof(sGridStatus), "Import");
      else
        snprintf(sGridStatus, sizeof(sGridStatus), "Ausgeglichen");

      char sWW[20];
      snprintf(sWW, sizeof(sWW), "%d°C", vWW);

      // Batterie inkl. SOC + optionale Zeit bis voll (Floatstunden -> h/min)
      bool has_charge_time = false;
      int charge_hours = 0;
      int charge_minutes = 0;
      if (!sZeit.empty() && sZeit != "unknown" && sZeit != "unavailable") {
        float hours_f = strtof(sZeit.c_str(), nullptr);
        if (hours_f > 0.0f && hours_f < 999.0f) {
          has_charge_time = true;
          charge_hours = (int) floorf(hours_f);
          charge_minutes = (int) lroundf((hours_f - charge_hours) * 60.0f);
          if (charge_minutes >= 60) { charge_minutes -= 60; charge_hours += 1; }
        }
      }

      char sBatExtra[48];
      if (has_charge_time) {
        snprintf(sBatExtra, sizeof(sBatExtra), "SOC: %d%%  |  %dh %02dmin", vSOC, charge_hours, charge_minutes);
      } else {
        snprintf(sBatExtra, sizeof(sBatExtra), "SOC: %d%%", vSOC);
      }

      // Layout-Helfer für strukturierte Boxen
      auto draw_section = [&](int x, int y, int w, int h, const char *title, const char *value, const char *subtitle = nullptr) {
        it.rectangle(x, y, w, h);
        it.printf(x + 12, y + 10, id(smallFont), esphome::display::TextAlign::TOP_LEFT, "%s", title);
        it.printf(x + w - 12, y + h / 2 + 10, id(myFont), esphome::display::TextAlign::BASELINE_RIGHT, "%s", value);
        if (subtitle != nullptr && subtitle[0] != '\0') {
          it.printf(x + w - 12, y + h - 14, id(tinyFont), esphome::display::TextAlign::BASELINE_RIGHT, "%s", subtitle);
        }
      };

      const int col_w = 240;
      const int row_h = 120;
      const int gap = 20;

      int row1_y = 20;
      int row2_y = row1_y + row_h + gap;
      int row3_y = row2_y + row_h + gap;

      draw_section(20,  row1_y, col_w, row_h, "PV-Ertrag", sPV, sPvExtra);
      draw_section(280, row1_y, col_w, row_h, "Hausverbrauch", sHaus, sHausExtra);
      draw_section(540, row1_y, col_w, row_h, "Batterie", sBat, sBatExtra);

      draw_section(20,  row2_y, col_w, row_h, "Netz", sGrid, sGridStatus);
      draw_section(280, row2_y, col_w, row_h, "Heizstab", sHeat, sHeatExtra);
      draw_section(540, row2_y, col_w, row_h, "EQA Ladung", sEQA);

      draw_section(20, row3_y, col_w, row_h, "Warmwasser oben", sWW);
      draw_section(280, row3_y, col_w, row_h, "Bezug", sBezug);
      draw_section(540, row3_y, col_w, row_h, "Einspeisung", sEins);

      it.printf(50, row3_y + row_h + 30, id(smallFont), "Batterie-SOC");

      // --- SOC-Balken (unterhalb, mit 10%-Ticks) ---
      const int bar_x = 50;
      const int bar_y = row3_y + row_h + 50;     // innerhalb 480 px Höhe bleiben
      const int bar_w = 700;
      const int bar_h = 20;

      // Rahmen
      it.rectangle(bar_x, bar_y, bar_w, bar_h);

      // Füllung
      int soc_clamped = clamp(vSOC);
      int fill_w = (bar_w * soc_clamped) / 100;
      if (fill_w > 0) it.filled_rectangle(bar_x, bar_y, fill_w, bar_h);

      // Ticks (unterhalb des Balkens, kurze Linien)
      for (int i = 0; i <= 10; i++) {
        int tx = bar_x + (bar_w * i) / 10;
        it.line(tx, bar_y + bar_h + 2, tx, bar_y + bar_h + 8);
      }
